#!/usr/bin/python3
BaseCaching = __import__('base_caching').BaseCaching
class FIFOCache(BaseCaching):
    def __init__(self):
        super().__init__()
    def put(self, key, item):
        if key is None or item is None:
            return
        if len(self.cache_data) >= BaseCaching.MAX_ITEMS:
            removed_item = next(iter(self.cache_data))
            del self.cache_data[removed_item]
            print("DISCARD: {}".format(removed_item))
        self.cache_data[key] = item
    def get(self, key):
        if key is None or key not in self.cache_data:
            return None
        return self.cache_data.get(key)
