#!/usr/bin/python3
""" Implementing the LIFO algorithm """
from collections import OrderedDict
BaseCaching = __import__('base_caching').BaseCaching


class LIFOCache(BaseCaching):
    """ Lifo algorithm taking place """

    def __init__(self):
        """ Initializing from the master class """
        super().__init__()
        self.cache_data = OrderedDict()

    def put(self, key, item):
        """ Putting an item to the cache """
        if key is None or item is None:
            return
        #If the key is not already in the cache
        if key not in self.cache_data:
            #If adding this item will exceed the maximum capacity of the cache
            if (len(self.cache_data) + 1) > self.MAX_ITEMS:
                #remove the last item inserted from the cache
                last_item, _ = self.cache_data.popitem(last=True)
                print("DISCARD: {}".format(last_item))
                #let us then update the item in the cache
        self.cache_data[key] = item
        #Move it to the end of the list
        self.cache_data.move_to_end(key, last=True)

    def get(self, key):
        """ Retrieving an Item """
        if key is None or key not in self.cache_data:
            return None
        self.cache_data[key]
